import React from "react";

import { Layout } from "antd";

import { Container, ContTest } from "./styles";

const { Content } = Layout;

export default function Home({ ...props }) {
  return (
    <Layout style={{ background: "transparent" }}>
      <Content>
        <Container>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
        </Container>
        <ContTest>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
          <div>asdasdasdas</div>
        </ContTest>
      </Content>
    </Layout>
  );
}
